sudo: required
services:
    - docker

before_install:
    - docker build -t michalhonc/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true michalhonc/react-test npm run test

after_success:
    - docker build -t michalhonc/multi-client ./client
    - docker build -t michalhonc/multi-nginx ./nginx
    - docker build -t michalhonc/multi-server ./server
    - docker build -t michalhonc/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push michalhonc/multi-client
    - docker push michalhonc/multi-nginx
    - docker push michalhonc/multi-server
    - docker push michalhonc/multi-worker
